### ISSUE TITLE
no matching package found.

### ISSUE THREAD

**Issue by fmronan** [endroid/EndroidOpenWeatherMapBundle#2]
[Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for endroid/openweathermap-bundle dev-master ->
  satisfiable by endroid/openweathermap-bundle[dev-master].
      - endroid/openweathermap-bundle dev-master requires endroid/openweather
  map ^1.0.7 -> no matching package found.
  Potential causes:
   - A typo in the package name
   - The package is not available in a stable-enough version according to you
  r minimum-stability setting
     see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussi
  on> for more details.
  Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further
  common problems.

**Comment by endroid** [comment]
Hi @fmronan sorry I can not reproduce this issue. Maybe you can try the latest version (1.0.8) which also supports guzzle 6.x.
